# Generated by Django 3.0.6 on 2020-05-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0003_auto_20200419_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInfo',
            fields=[
                ('problemId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectID', models.IntegerField()),
                ('problemTitle', models.CharField(max_length=500)),
                ('problemText', models.CharField(max_length=2000)),
                ('imageLink', models.CharField(max_length=1000)),
                ('sampleDummyInput', models.CharField(max_length=500)),
                ('sampleDummyOutput', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('problemCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProblemDeatils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailCount', models.IntegerField()),
                ('success', models.BooleanField()),
                ('solution', models.CharField(max_length=20000)),
                ('timeTaken', models.CharField(max_length=20)),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemInfo')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.users')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseInfo',
            fields=[
                ('testCaseId', models.AutoField(primary_key=True, serialize=False)),
                ('sampleInput', models.CharField(max_length=500)),
                ('sampleOutput', models.CharField(max_length=500)),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemInfo')),
            ],
        ),
    ]
