# Generated by Django 3.0.5 on 2020-04-19 11:59

import authen.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('resetToken', models.CharField(max_length=20)),
                ('valid', models.BooleanField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration', models.DateTimeField(default=authen.models.s_tomorrow)),
            ],
        ),
    ]
