# Generated by Django 3.0.5 on 2020-04-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='resetToken',
            field=models.CharField(max_length=200),
        ),
    ]
